- name: Install mongo
  hosts: mainserver
  tasks:
    - file: path=~/mongo state=directory
    - copy:
        src: docker-compose.mongo.yml
        dest: ~/mongo/docker-compose.yml
        mode: 0644
    - docker_compose:
        project_src: ~/mongo/
        state: absent
      register: output
    - docker_compose:
        project_src: ~/mongo/
        state: present
      environment:
        mongo_username: "{{mongo_username}}"
        mongo_password: "{{mongo_password}}"
      register: output
    - debug:
        var: output
