- hosts: all

  tasks:

    - name: install drone CI
      command: >
               docker run 
               --volume=/var/run/docker.sock:/var/run/docker.sock 
               --volume=/var/lib/drone:/data 
               --env=DRONE_GITHUB_SERVER=https://github.com 
               --env=DRONE_GITHUB_CLIENT_ID={{drone_githab_client_id}} 
               --env=DRONE_GITHUB_CLIENT_SECRET={{drone_githab_client_secret}} 
               --env=DRONE_RUNNER_CAPACITY=2 
               --env=DRONE_SERVER_HOST={{drone_subdomain}}.{{domain_name}}
               --env=DRONE_SERVER_PROTO=https 
               --env=DRONE_TLS_AUTOCERT=true 
               --env=DRONE_USER_CREATE=username:{{drone_admin_username}},admin:true,token:{{drone_admin_token}}
               --publish=80:80 
               --publish=443:443 
               --restart=always 
               --detach=true 
               --name=drone 
               drone/drone:1

